In [1]:
import numpy as np

In [2]:
a = np.array([1,234,67])

In [4]:
a.shape

(3,)

In [5]:
np.full((2,3),8.)

array([[8., 8., 8.],
       [8., 8., 8.]])

In [7]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
%timeit np.ones((3,3))

1.31 µs ± 44.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [10]:
%timeit np.full((3,3),1)

1.45 µs ± 27.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [12]:
ran = np.random.random((3,4))

In [19]:
filter = (ran>0.5)
ran[filter]

array([0.55484761, 0.88092493, 0.63988461, 0.64403064, 0.61271577])

In [23]:
ran = np.array(ran,dtype=np.float32)

In [25]:
ran

array([[0.3864105 , 0.01843747, 0.5548476 , 0.88092494],
       [0.6398846 , 0.1251825 , 0.23848878, 0.08719371],
       [0.64403063, 0.6127158 , 0.47566125, 0.4940514 ]], dtype=float32)

In [26]:
ran.mean()

0.4298191

In [28]:
ran.mean(axis=1)

array([0.46015513, 0.2726874 , 0.55661476], dtype=float32)

In [32]:
ran.sum(axis = 1)

array([1.6703258 , 0.75633574, 1.2689977 , 1.4621701 ], dtype=float32)

In [34]:
np.median(ran,axis=1)

array([0.47062904, 0.18183564, 0.5533836 ], dtype=float32)

### Broadcasting

In [43]:
a = np.zeros((2,3))
b = np.ones(1,)

In [44]:
print(a+ b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [51]:
add_cols = np.array([[0,1]])

In [52]:
add_cols.T

array([[0],
       [1]])

In [53]:
a + add_cols.T

array([[0., 0., 0.],
       [1., 1., 1.]])

### Efficiency

In [54]:
from timeit import Timer

size = 1000000
timeits = 1000

In [55]:
arr = np.arange(size)

In [56]:
timer = Timer('arr.sum()','from __main__ import arr')

timer.timeit(timeits)/timeits

0.000799852196010761

In [57]:
alist = list(range(size))

In [58]:
timer_list = Timer('sum(alist)', 'from __main__ import alist')
timer_list.timeit(timeits)/timeits

0.006542303764028474

# Ogrid

In [62]:
x, y = np.ogrid[:3,:2]
print(x.shape, y.shape)
y

(3, 1) (1, 2)


array([[0, 1]])